version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
